function createMockHwh5ext() {
  var listener = null;
  var seq = 1;
  var nextMessageId = 1000;
  var nextMessageSeq = 10;

  function emit(event) {
    if (!listener || !listener.onMessage) return;
    listener.onMessage(
      Object.assign(
        {
          seq: seq++,
          emittedAt: new Date().toISOString(),
        },
        event,
      ),
    );
  }

  return {
    getSessionMessage: function getSessionMessage(params) {
      return Promise.resolve({
        content: [
          {
            id: 1,
            welinkSessionId: params.welinkSessionId,
            role: 'assistant',
            content: 'This viewer is mounted from dist/lib/index.js via require().',
            messageSeq: 1,
            createdAt: new Date().toISOString(),
            parts: [
              {
                partId: 'history-part-1',
                partSeq: 1,
                type: 'text',
                content: 'This viewer is mounted from dist/lib/index.js via require().',
              },
            ],
          },
        ],
      });
    },

    registerSessionListener: function registerSessionListener(params) {
      listener = params;
      emit({
        type: 'session.status',
        welinkSessionId: String(params.welinkSessionId),
        sessionStatus: 'idle',
      });
    },

    unregisterSessionListener: function unregisterSessionListener() {
      listener = null;
    },

    sendMessage: function sendMessage(params) {
      var text = params.content || '';
      var answer =
        'Mock assistant received: ' +
        text +
        '\n\nThis streamed message is generated by mockHwh5ext.';

      var messageId = 'mock-assistant-' + (++nextMessageId);
      var messageSeq = ++nextMessageSeq;
      var partId = 'part-' + messageId;
      var chunks = answer.match(/.{1,10}/g) || [];
      var index = 0;

      emit({
        type: 'session.status',
        welinkSessionId: String(params.welinkSessionId),
        sessionStatus: 'busy',
      });

      return new Promise(function (resolve) {
        var timer = setInterval(function () {
          if (index < chunks.length) {
            emit({
              type: 'text.delta',
              welinkSessionId: String(params.welinkSessionId),
              messageId: messageId,
              messageSeq: messageSeq,
              role: 'assistant',
              partId: partId,
              partSeq: 1,
              content: chunks[index],
            });
            index += 1;
            return;
          }

          clearInterval(timer);
          emit({
            type: 'text.done',
            welinkSessionId: String(params.welinkSessionId),
            messageId: messageId,
            messageSeq: messageSeq,
            role: 'assistant',
            partId: partId,
            partSeq: 1,
            content: answer,
          });
          emit({
            type: 'session.status',
            welinkSessionId: String(params.welinkSessionId),
            sessionStatus: 'idle',
          });

          resolve({
            id: ++nextMessageId,
            welinkSessionId: params.welinkSessionId,
            role: 'user',
            content: params.content,
            messageSeq: messageSeq - 1,
            createdAt: new Date().toISOString(),
          });
        }, 120);
      });
    },

    stopSkill: function stopSkill(params) {
      emit({
        type: 'session.status',
        welinkSessionId: String(params.welinkSessionId),
        sessionStatus: 'idle',
      });
      return Promise.resolve({
        welinkSessionId: params.welinkSessionId,
        status: 'aborted',
      });
    },

    sendMessageToIM: function sendMessageToIM() {
      window.alert('Mock: sent to IM');
      return Promise.resolve({ status: 'success' });
    },

    controlSkillWeCode: function controlSkillWeCode(params) {
      console.log('[mockHwh5ext] controlSkillWeCode:', params.action);
      return Promise.resolve({ status: 'success' });
    },

    replyPermission: function replyPermission(params) {
      emit({
        type: 'permission.reply',
        welinkSessionId: String(params.welinkSessionId),
        permissionId: params.permId,
        response: params.response,
      });
      return Promise.resolve({
        welinkSessionId: params.welinkSessionId,
        permissionId: params.permId,
        response: params.response,
      });
    },
  };
}

module.exports = {
  createMockHwh5ext: createMockHwh5ext,
};
